### ISSUE TITLE
[mini epic] Improve CI builds:  use containers, add format checks, etc.

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/libsys-airflow#394]
Per thread in slack (https://stanfordlib.slack.com/archives/C04EZLBMLQN/p1683665868232099?thread_ts=1683663418.751839&cid=C04EZLBMLQN), we want to improve CI builds:

- [ ] have our GH action use our docker containers for our CI build, as our deployments will  ( https://docs.github.com/en/actions/using-containerized-services/about-service-containers may help)
    - per standup discussion 5/16/23, we've decided this is not worth it because:
        - we believe the vendor_load database to be stable now ... no new migrations expected
        - our tests are very "unit-y" and use sqlite and mocking, so spinning up the whole megillah in docker to run the tests seems unnecessary.
    - [ ] run alembic migrations in docker containers as part of the build, even if the tests don't need them -- this is a way to ensure we will find out if the alembic/migrations history ends up with multiple head pointers, for example.
        - this should be a separate workflow (?)
        - issue to make this part of deployment:  #372
- [x] have our GH actions also do both of these (as a separate workflow):
    - [x] format checking (using `black`) - see PRs #412, #413, #414
    - [x] linting (using `flake8` or possibly replacing with `ruff`) - see PRs #423 and #424
- [x] do NOT ignore rule F401 about unused import statements. -- see PR #425
- [ ] have our formating standardize on organization of import statements in our files.  (plugin for flake8)
    - I tried `isort`, `flake8-isort` and `flake8-import-order` and they all seemed non-trivial to configure.  For example, for `flake8-isort`, I removed a blank line it complained about, and then got a flake8 error.   I even tried setting the profile to black, and it didn't help.   Thus, punting.

These could be split into separate tickets, or they could be separate PRs on this ticket.

![image.png](https://images.zenhubusercontent.com/5d89272aae87b600015057e7/5e2bb5f1-cdc1-42e9-b969-c34e0b8cc31f)

**Comment by jmartin-sul** [comment]
here's an example of using `black` in CircleCI to find lint that `black` would correct: https://github.com/sul-dlss/dlme-airflow/blob/main/.circleci/config.yml#L39-L42 (the default mode is to just do the corrections, this mode returns a non-zero exit code if `black` finds things it'd change: `poetry run black --diff --check .`)

**Comment by jmartin-sul** [comment]
here's an example where `flake8` (if we stick with that instead of switching to `ruff`) is configured using `setup.cfg`, so that running `flake8` without any options carves out the lint exceptions we want, which makes it easier to just run the same command in both CI and a dev's laptop environment: https://github.com/sul-dlss/dlme-airflow/blob/main/setup.cfg

i'm happy to ticket this separately if desired, or to add it to the description's checklist if we want to lump it in here, but this is an example of using `mypy` to do typechecking:
* invocation in CI: https://github.com/sul-dlss/dlme-airflow/blob/main/.circleci/config.yml#L56-L59
* inclusion in dev dependencies: https://github.com/sul-dlss/dlme-airflow/blob/main/pyproject.toml#L30-L31 (will require re-generating `poetry.lock`)
* configuration to ignore missing imports, so that we don't get a bunch of type errors around imported 3rd party code: https://github.com/sul-dlss/dlme-airflow/blob/main/setup.cfg#L10-L11

**Comment by ndushay** [comment]
what is .setup.cfg and do I need to add black to it?   From a quick lookup, it seems like it has to do with distributed modules, and I don't think we'll care about black in that context.

**Comment by ndushay** [comment]
@jmartin-sul if you're interested in `mypy`, then I think you should ticket it separately.  I'm not going to do it as part of this ticket.

**Comment by jmartin-sul** [comment]
> @jmartin-sul if you're interested in `mypy`, then I think you should ticket it separately. I'm not going to do it as part of this ticket.

that's fine, will do!  i was sort of thinking i'd ticket it and deal with it separately (and had been looking into it a bit yesterday), but should've mentioned that explicitly at standup or in a comment here.

**Comment by ndushay** [comment]
extra plugin for flake8 for ordering of imports?

**Comment by ndushay** [comment]
I am declaring this ticket done, as the remaining items will NOT be pursued at this time.
